### ISSUE TITLE
更新1.2.0之后不适配之前版本

### ISSUE THREAD

**Issue by BestCoderXQX** [VeiZhang/Downloader#3]
项目中如果使用 compile 'com.excellence:downloader:+'的  用法还是1.1.0的话会出错

**Comment by VeiZhang** [comment]
@BestCoderXQX 使用compile 'com.excellence:downloader:+，查询路径`.gradle\caches\modules-2\files-2.1\com.excellence\downloader`是否下载了1.2.0；最新的1.2.0：改动了初始化的接口
